### ISSUE TITLE
Array with hole support

### ISSUE THREAD

**Issue by tiansh** [marcello3d/node-tosource#19]
Array with last element as a hole will generate wrong output.

``` javascript
eval(tosource(Array(3))).length // should be 3, but get 2 
```

**Comment by marcello3d** [comment]
How would you expect this to serialize?

**Comment by tiansh** [comment]
`Array(3)` should be serialized to `[, , ,]`.

**Comment by tiansh** [comment]
Specification: http://www.ecma-international.org/ecma-262/7.0/index.html#sec-array-initializer

**Comment by marcello3d** [comment]
ES2016 is a bit newer than I'm supporting… what's the browser support like?

**Comment by tiansh** [comment]
Actually, this behavior had been [defined in ES5](http://www.ecma-international.org/ecma-262/5.1/index.html#sec-11.1.4) (I'm not sure what ES3 does say). IE 10+ and all other browsers support it. (IE <=9 is buggy)
