### ISSUE TITLE
Numbers casted to Strings

### ISSUE THREAD

**Issue by DoNck** [marcello3d/node-tosource#20]
Hi,

I want to inject the following options to a google chart within an html page:
``
          slices: {
            0: { color: 'yellow' },
            1: { color: 'transparent' }
          }
``
(see [gchart help](https://developers.google.com/chart/interactive/docs/gallery/piechart#removing-slices))

So I first build a slice object:
```
slices= {};
slices[0]={ color: 'yellow' }; 
slices[1]={ color: 'transparent' };
```

Then I call ``toSource(slices)`` and get the following result:

``
{ "0":{ color:"yellow" },
  "1":{ color:"transparent" } }
``

Sadly, google charts doesnt like the String keys instead of integers. I'll find a workaround for that, but I think toSource is misbehaviying. I know it is not really part of a standard, but I can't see why the integers should get casted into Strings. Firefox's toSource() is keeping integers as integers, I think it would make more sense to do so.

**Comment by marcello3d** [comment]
Sounds like a good bug to fix, please contribute a pull request! :-)

**Comment by Taraflex** [comment]
@marcello3d It's not a mistake. When an object property is set, any variable tries to be cast to the string. Simple example.
`var a = {[(new Object)]:'test'}; console.log(a)`
Print `{[object Object]: "test"}`

**Comment by kannagikazuko** [comment]
`Object` keys are always converted to strings and `Symbol`s. You are probably looking for the functionality of a `Map`. I vote to close this issue.
