### ISSUE TITLE
NPM package is missing `dist` folder

### ISSUE THREAD

**Issue by overlookmotel** [marcello3d/node-tosource#25]
Package on NPM (`tosource@2.0.0-alpha.1`) is missing the `dist` folder, so does not function.

The NPM package also includes `src` folder, which is unnecessary. It could be excluded from the NPM release with a `files` field in `package.json`, or an `.npmignore` file.

**Comment by marcello3d** [comment]
Good catch!

**Comment by marcello3d** [comment]
@overlookmotel should be packaged properly in `2.0.0-alpha.2`, let me know if that works for you. I left the src folder in there because they're used by sourcemaps and makes it easier to debug.
